### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Kra1o5**

### CODE REVIEW

**Comment by R0rt1z2** [comment]
Hi @Kra1o5,

Thanks for your pull-request, we really appreciate your contributions.
Before merging the PR, have you tried all those changes (I guess you have an M8 or M10 to test them on)?
Switching to full enforcing SELinux requires a good sepolicy and I'm afraid we weren't actually using that (too lazy to fix it) so can you confirm everything works with enforcing SELinux (specially HDMI)?
As for the codename, we were already using `karin` but we noticed there were more devices using that codename ([Sony Xperia Z4 Tablet LTE](https://wiki.lineageos.org/devices/karin)) so we just created another device codename (following bq's dragon ball codenames). If you really think we should use the original codename I'll change it.

Best regards.
Roger.

**Comment by Kra1o5** [comment]
Hi @R0rt1z2 ,

Yes, I have both M8 and M10, but only tested in M8 at this time.
All on this commit its working fine (boots, BT and Wlan are ok, D2TW, back from standby, charging).
I cannot test HDMI (not have a mini HDMI one).
I think its better to keep the original codename of the devices.

Greetings,

**Comment by R0rt1z2** [comment]
> Hi @R0rt1z2 ,
> 
> Yes, I have both M8 and M10, but only tested in M8 at this time.
> All on this commit its working fine (boots, BT and Wlan are ok, D2TW, back from standby, charging).
> I cannot test HDMI (not have a mini HDMI one).
> I think its better to keep the original codename of the devices.
> 
> Greetings,

Alright thanks for the quick feedback. 
I'll try the build with those commits in my M8 and will try HDMI. If everything goes OK I'll merge your PR.
Thanks again.

**Comment by jmpfbmx** [comment]
Hi @Kra1o5
How are you?
Would you let me write to you by telegram pls?
We can do a group and we discuss about these tablets easier than do it by here if you see it alright.
PD: This is my telegram profile t.me/jmpf_bmx
Thanks,
Regards Jose

**Pull request merged**
